# Generated by Django 2.2 on 2019-07-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20)),
                ('telefono', models.IntegerField(max_length=20)),
                ('ciudad', models.TextField(max_length=20)),
                ('servicio', models.TextField(max_length=20)),
                ('breve_descripcion', models.TextField(max_length=100)),
            ],
        ),
    ]
