# Generated by Django 2.2 on 2019-07-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='imagen',
            field=models.ImageField(default='imagenes/None/no-img.jpg', upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='servicio',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='info',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
