# Generated by Django 2.2 on 2019-07-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0002_auto_20190722_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='nro',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='breve_descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='info',
            name='servicio',
            field=models.TextField(max_length=100),
        ),
    ]
